### ISSUE TITLE
Using JFile and JFolder instead of native functions?

### ISSUE THREAD

**Issue by zero-24** [jissereitsma/media-manager-improvement#5]
Here:
https://github.com/jissereitsma/media-manager-improvement/blob/master/administrator/components/com_media/models/file/adapter/local.php

We have some places were we use the PHP native functions `rename`, `copy`, `file_put_contents` etc.

Should we not better move that code to use JFile and JFolder?

**Comment by jissereitsma** [comment]
Actually, both JFile and JFolder are non-namespaced and not fit for working together with future developments like FlySystem. Indeed, things are a bit duplicate right now. We hope to get more insights (discussions, brainstorms, beer sessions) on adding a modern abstract of filesystem manipulations :)

**Comment by zero-24** [comment]
Closing as the repo is moved back to https://github.com/joomla-projects/media-manager-improvement ;)
