### ISSUE TITLE
Navigation using the folder icons on the right hand side don't work

### ISSUE THREAD

**Issue by zero-24** [jissereitsma/media-manager-improvement#6]
Using the folder icons on the right hand side don't work. It just append a `#` to the URL.

![navigatin_using_the_folders_dont_work](https://cloud.githubusercontent.com/assets/2596554/14777686/fc439776-0ace-11e6-92f4-02b1e56323cf.PNG)

Opening images works as expected.

**Comment by jissereitsma** [comment]
Thanks. Note that this is still all in development, so the issue is known and should be picked up soon.

**Comment by zero-24** [comment]
Closing as the repo is moved back to https://github.com/joomla-projects/media-manager-improvement ;)
